### ISSUE TITLE
CI broken

### ISSUE THREAD

**Issue by mfro0** [vinriviere/fvdi#13]
The CI workflow is broken. I'm not familiar with the scripts, but it appears older packages at savannah.gnu.org regularly get moved into the freetype-old directory?

As it stands, one of the packages required for the CI process just moved and isn't found anymore, causing the CI process to bail out prematurely.

@th-otto : is that something you could look into (if time permits), please?

**Comment by th-otto** [comment]
On Samstag, 29. Januar 2022 13:56:49 CET Markus wrote:
> @th-otto : is that something you could look into (if time permits), please?

Should be done. Have to check once built is complete.

Should that happen again: it's just a one-liner in one of the install-scripts.

**Comment by mfro0** [comment]
I didn't want to fiddle with a script I don't know, but if it's really just a one-liner I can do that next time myself.
Thank you!
