### ISSUE TITLE
Fonts do not sit correctly on baseline

### ISSUE THREAD

**Issue by chrisridd** [vinriviere/fvdi#25]
I tried to draw a single line of text in multiple fonts, aligned at the baseline. The results are not great, using 40pt text just to make it a bit more obvious:

![snap015](https://user-images.githubusercontent.com/237257/156050960-e33736f6-b719-46ce-883a-fac61d341754.png)

The red line is my baseline. I'm doing:

	vst_alignment(handle, 0, 0, &dummy, &dummy); // left, baseline

	vst_font(handle, fontid1);
	vst_point(handle, 40, &dummy, &dummy, &dummy, &dummy);
	v_ftext(handle, xstart, ystart, "DejaVu");

	vst_font(handle, fontid2);
	vst_point(handle, 40, &dummy, &dummy, &dummy, &dummy);
	xstart += (width-of-DejaVu-text);
	v_ftext(handle, xstart, ystart, "Bookerly");

	vst_font(handle, fontid3);
	vst_point(handle, 40, &dummy, &dummy, &dummy, &dummy);
	xstart += (width-of-Bookerly-text);
	v_ftext(handle, xstart, ystart, "Helvetica");

NVDI 5 does get the vertical alignment correct.

The `ft2_text_render()` assembles the character bitmaps into a bigger buffer and blits it to the screen using a vertical offset from `extra.distance`. The computation of the `extra.distance` fields **seems** to be OK, but the more I read about metrics and sizes at freetype.org the less I feel I know! Is the bbox the right way to measure things, or just the ascent+descent?

The errors are reasonably significant (up to 16 pixels in my screenshot!), so they can't be just simple rounding errors.

**Comment by chrisridd** [comment]
After the patch in #26 this is what I get:

![snap017](https://user-images.githubusercontent.com/237257/156235416-d1efaffa-1a2f-4e1f-bdf1-bf45f9b30330.png)

**Comment by mfro0** [comment]
Looks better now for me as well. Thank you for your contribution!

**Comment by chrisridd** [comment]
Thanks! And it looks like moving a variable declaration down broke on an older compiler - apologies for that.
